'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [mode, setMode] = useState<'login'|'signup'>('login')
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); const supabase = createClient(); const result = mode === 'login' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { emailRedirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL || `${window.location.origin}/auth/callback` } }); if (result.error) { setError(result.error.message.toLowerCase().includes('confirm') ? 'Verifye email ou an anvan ou kontinye.' : 'Email oswa modpas la pa valab.'); return } window.location.href = mode === 'login' ? '/account' : '/login?created=1' }
  async function google() { const supabase = createClient(); await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL || `${window.location.origin}/auth/callback` } }) }
  return <main className="auth-page"><div className="auth-card"><a className="brand" href="/">NENE STORE <span>ET CELESTE COMPANY</span></a><p className="eyebrow">KONT KLIYAN</p><h1>{mode === 'login' ? 'Bon retou.' : 'Kreye kont ou.'}</h1><p className="auth-copy">Sove kòmand ou yo epi jwenn sèvis ou pi vit.</p><button className="google-button" onClick={google}>Kontinye ak Google</button><div className="auth-divider"><span>oswa</span></div><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Modpas<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} /></label>{error && <p className="payment-error" role="alert">{error}</p>}<button className="checkout" type="submit">{mode === 'login' ? 'Konekte' : 'Kreye kont'}</button></form><button className="auth-switch" onClick={()=>setMode(mode === 'login' ? 'signup':'login')}>{mode === 'login' ? 'Ou poko gen kont? Kreye youn' : 'Ou deja gen kont? Konekte'}</button></div></main>
}
